# SPDX-FileCopyrightText: 2025 The Wallet Verifier Test Web Authors
# SPDX-License-Identifier: CC0-1.0

---
policies:
  - type: commit
    spec:
      dco: true
      gpg:
        required: true
      header:
        length: 200
        imperative: true
        case: lower
        invalidLastCharacters: .
      body:
        required: false
      conventional:
        types:
          [
            "chore",
            "ci",
            "docs",
            "perf",
            "refactor",
            "style",
            "test",
            "release",
          ]
        scopes: [".*"]
        descriptionLength: 92
