[allowlist]
description = "Global allow list"
regexTarget = "line"
regexes = ['''ospo\@digg\.se''']

[[rules]]
id = "digg-internal-hosts"
description = "Digg internal host names"
regex = '''([a-zA-Z0-9]+\.)*digg\.se'''
keywords = ["digg"]
tags = ["DIGG"]
