[allowlist]
description = "Global allow list"
regexTarget = "match"
regexes = [
    '''^digg\.se$''',
    '''^ospo\@digg\.se$'''
]

[[rules]]
id = "digg-internal-hosts"
description = "Digg internal host names"
regex = '''([a-zA-Z0-9]+\.)*digg\.se'''
keywords = ["digg"]
tags = ["DIGG"]

[rules.allowlist]
paths = ["docker/WSL.se.adoc"]

[[rules]]
id = "digg-email-address"
description = "Digg email address"
regex = '''([a-zA-Z0-9]+)\@([a-zA-Z0-9]+\.)*digg\.se'''
keywords = ["digg"]
tags = ["DIGG"]
