services:
  verifier-backend:
    image: ghcr.io/eu-digital-identity-wallet/eudi-srv-web-verifier-endpoint-23220-4-kt:latest
    container_name: verifier-backend
    ports:
      - "8080:8080"
    environment:
      VERIFIER_PUBLICURL: "https://localhost:8080"
      VERIFIER_RESPONSE_MODE: "DirectPost"

  verifier-ui:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: verifier-ui
    ports:
      - "4300:4300"
    environment:
      - HOST_API="https://localhost"

  verifier-haproxy:
    image: haproxy:2.8.15
    container_name: verifier-haproxy
    ports:
      - "443:443"
    volumes:
      - ./haproxy.conf:/usr/local/etc/haproxy/haproxy.cfg
      - ./haproxy.pem:/etc/ssl/certs/mysite.pem
