# SPDX-FileCopyrightText: 2024 Digg - The Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

name: wallet-verifier-test-web

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  publish-container-image: # only on semver tag
    permissions:
      contents: read
      packages: write
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/publishimage.yml

